#!/usr/bin/env python

def build(bld):
	prog = bld(features='cc cprogram')
	# symbolic name used to reference this object
	prog.name = 'park'
	prog.includes  = '/usr/include/SDL'
	# name of the resulting program
	prog.target = 'park'
	prog.source =  'main.vala log.vala settings.vala scene.vala'
	# libraries to link against
	prog.uselib = 'GTK+ GEE GLIB SDL JASON SDL-IMAGE'
	# Vala packages to use
	prog.packages = 'gtk+-3.0 gee-1.0 glib-2.0 json-glib-1.0 gl glu gsl sdl sdl-image'
	# Extra vapi dirs
	#prog.vapi_dirs = '../my_lib'
	# Enable threading
	prog.threading = True
